### ISSUE TITLE
Score Format

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#10]
1. Change each question's score range to 1 - 10. Interval is 1.

2. There's a space before the first person in the leaderboard.

**Comment by sruan2** [comment]
It seems that the perfect matched answer is scored at 9 (rather than 10). Please see that screenshot attached:
![image](https://user-images.githubusercontent.com/5453117/34332105-ea749e18-e967-11e7-8f0a-34bf374c602c.png)

**Comment by Zhengneng** [comment]
I guess that's due to the upper case Mechanical. See my screenshot this evening.

![image](https://user-images.githubusercontent.com/3099927/34336193-0dcc13a4-e90a-11e7-9da9-d2094e276b7c.png)

**Comment by sruan2** [comment]
I see. We should do some basic word processing then such as lowercase and stemming. I will close this issue and mark this in issue #9
