### ISSUE TITLE
Implement State Machine

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#14]
See the google doc named "QuizBot Conversation Design" for specifications.

**Comment by Zhengneng** [comment]
I've fixed a couple things so right now it's following 80-90% of the conversation flow:
1) No longer can hack score by re-entering correct answer
2) Added subject selections but it's fake still no subject classification yet
3) After a question was asked, no user can break the chat flow unless he/she answers the question with a score comes up

**Comment by sruan2** [comment]
![image](https://user-images.githubusercontent.com/5453117/34451415-bddeece0-ed5f-11e7-9a73-4ad88f571b3e.png)
Great job! One minor typo: history spelling.
