### ISSUE TITLE
 report bug/ wrong scoring/ wrong classification feature

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#22]

**Comment by sruan2** [comment]
make a button called "Report" in the main menu which has three sub buttons "Wrong Scoring", "Wrong Question Classification", "Others"

**Comment by Zhengneng** [comment]
I thought you also mentioned that at max 3 items are allowed in the main menu and at max 2 nested items could be added to it right?
https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/persistent-menu

**Comment by sruan2** [comment]
That's my hunch. I'm not certain. We can play with it.

**Comment by sruan2** [comment]
New design idea: make a button "“wait, but I got it right”

**Comment by sruan2** [comment]
I added a report button within send_why_quickreply function:
{
"content_type": "text",
"title": "Wait, I got it right...",
"payload": "REPORT"
},
You can implement the report function there.

**Comment by Zhengneng** [comment]
ok!
