### ISSUE TITLE
Graphical design for scores and leaderboard (refer to Edwin)

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#37]
![image.png](https://images.zenhubusercontent.com/5a3a08148a75884b908bb845/fca08e1d-f110-4bd5-b9a1-74545260698d)

**Comment by sruan2** [comment]
Contact designers.

**Comment by sruan2** [comment]
Make the leaderboard picture larger (occupy ⅔ of the screen)

**Comment by Zhengneng** [comment]
What buttons should we send after showing leaderboard pic?
