### ISSUE TITLE
change "hint" to multiple choice questions

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#44]

**Comment by sruan2** [comment]
我是指hint button出现在问题后面，这样用户不会回答可以先看hint，当然用户也可以直接回答问题。

**Comment by Zhengneng** [comment]
我觉得可以，但有个问题，当用户看到有一个hint的按钮弹出来之后，我觉得他们会不会不知所措呢？应该会有种感觉是不是点完之后跳过这个有button的界面之后才可以对话框输入答题？

**Comment by Zhengneng** [comment]
hint的内容就是support的内容吧？

**Comment by sruan2** [comment]
我觉得会有这个concern，所以我们可能要加个instruction，或者进行一下用户测试。我先把这个issue重新打开

**Comment by sruan2** [comment]
我加了一个"I need a hint ..." button, 当用户点击的时候，我们就给他把问题的四个选项都出成多选题给他，我已经把data格式改成json了，直接从self.D1KB, self.D2KB, self.D3KB读错误选项就可以，别忘了做database的logging
