### ISSUE TITLE
Conversation design

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#5]

**Comment by sruan2** [comment]
Learn from English with Edwin.

Things we can add:
better introduction, feedback (encouragement), emoji, instructions, study plan etc.

**Comment by Zhengneng** [comment]
I really enjoy this chat flow. but one question, i couldn't do multiple choice after changing my mind giving up?

![image](https://user-images.githubusercontent.com/3099927/35881879-21d43288-0b37-11e8-8cfb-564ab0df863c.png)

**Comment by sruan2** [comment]
Good point, I improve it by giving multiple choice after the user clicks on "No, I'll try again!"
