### ISSUE TITLE
Duplicate users in leaderboard

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#53]
![image.png](https://images.zenhubusercontent.com/5a3a08148a75884b908bb845/c0b26c4a-4b31-42c3-98b7-85df797866df)

**Comment by sruan2** [comment]
The unfortunate catch I found was that Facebook uses different user_ids for Facebook Profile (which is used for login) and Messenger. A same account would have 2 different user_ids, and the bot only receives the Messenger user_id from the Messenger API. 

This may be the reason.

**Comment by sruan2** [comment]
Two Yeshuangs, two zhengnengs, two sherrys. What happened!!??

![img_5268](https://user-images.githubusercontent.com/5453117/35789352-78d0be78-09f0-11e8-851f-662936d25a3a.jpg)

**Comment by sruan2** [comment]
Can we at least remove duplicate users from the leaderboard manually? It doesn't look nice for a demo

**Comment by Zhengneng** [comment]
removed

**Comment by Zhengneng** [comment]
![image](https://user-images.githubusercontent.com/3099927/35868148-936690ac-0b10-11e8-9fef-242888ee9cb7.png)

**Comment by sruan2** [comment]
Two Sherry Ruans?

**Comment by Zhengneng** [comment]
hmm,
So I think essentially this is an entity resolution problem - How are we going to merge two different records by knowing they are essentially the same entity?

**Comment by sruan2** [comment]
Why are there two ids for each user? Is it because of the reason I posted before (The unfortunate catch I found was that Facebook uses different user_ids for Facebook Profile (which is used for login) and Messenger. A same account would have 2 different user_ids, and the bot only receives the Messenger user_id from the Messenger API.)???

**Comment by sruan2** [comment]
I will get someone to use QuizBot from the Messenger app and from the computer. Let's see if we can reproduce this bug.

**Comment by Zhengneng** [comment]
I am afraid that's the reason. yes, let's test it tonight.

**Comment by Zhengneng** [comment]
Reply from Facebook.
***********************************************************************************************************
Thanks for reaching out.

I verified the user IDs you reported and they are correct.

The user ids you are receiving are Page-scoped User IDs. As such, the IDs for the same person will be different if linked to different pages.

You can read more about this here: https://developers.facebook.com/docs/messenger-platform/identity/id-matching, and here: https://developers.facebook.com/docs/apps/for-business.

Hope this helps.

**Comment by Zhengneng** [comment]
I will dive into it and have it resolved.

**Comment by sruan2** [comment]
Just checked it now, two "Olivia"s...
![img_5315](https://user-images.githubusercontent.com/5453117/36069290-89590426-0e9b-11e8-9c4d-26cb63f7bf82.jpg)

**Comment by Zhengneng** [comment]
Now she's gone.

**Comment by Zhengneng** [comment]
I didn't clean up the DB completely last week.
