### ISSUE TITLE
"why" is hardcoded

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#54]

**Comment by sruan2** [comment]
when I type "why" when answering a question, it gives me the explanation instead of scoring my reply.

**Comment by sruan2** [comment]
We should think about what is an appropriate way to deal with this.

**Comment by Zhengneng** [comment]
So what do you want it to be when user asks why in to-answer mode? Giving score 0? that's doable.

**Comment by sruan2** [comment]
Yes

**Comment by sruan2** [comment]
Closing this issue because this is basically the quick reply payload issue. See issue #55

**Comment by sruan2** [comment]
solved after rewriting chat code in yml
