### ISSUE TITLE
Add Postback to button

### ISSUE THREAD

**Issue by Zhengneng** [sruan2/QuizBot#55]

**Comment by sruan2** [comment]
Please see how I used it in respond_to_postback function within chatbot.py:

    if payload == "GET_STARTED_PAYLOAD":
        send_ready_go(sender_id, "Hi! Welcome! I'm your personal tutor Mr Owl and \
            I'm here to help you master science! Ready? Go!"+u'\uD83D\uDE0A')
        
    elif payload == "YUP_IM_READY":
        update_status(mysql, sender_id, 1)
        choose_mode_quick_reply(sender_id)

**Comment by Zhengneng** [comment]
Sure!

**Comment by sruan2** [comment]
Wait... It seems that postback only works for "get started". If you look at logs, only "Get Started" is received as postback, the rest quick replies are all messages. We need to do more research...

**Comment by Zhengneng** [comment]
Yes that's what I was aware of. I was thinking we have to make "type :  postback" explicitly but it couldn't work with quick replies hand in hand

**Comment by sruan2** [comment]
But then "type: postback" will make the code crash because it's not supported by Facebook Messenger.

**Comment by Zhengneng** [comment]
it's supported by other Facebook Messenger buttons but not quick_replies I guess.

**Comment by sruan2** [comment]
是的，menu和刚开始的get started都支持postback，但对话中的quick replies button不支持

**Comment by sruan2** [comment]
Finally figured this out! Good job!
