### ISSUE TITLE
Emoji not visible in my device

### ISSUE THREAD

**Issue by Zhengneng** [sruan2/QuizBot#72]
Device : ThinkPad T450s

![image.png](https://images.zenhubusercontent.com/5a3b03118a75884b908bd215/4f623147-b8d9-4815-897e-3a8d6a899427)

![image.png](https://images.zenhubusercontent.com/5a3b03118a75884b908bd215/caff9448-10a1-4b26-8f72-b9057aab65dc)

**Comment by sruan2** [comment]
Can you try Engish with Edwin on your computer and see if their emojis are shown correctly @Zhengneng

**Comment by Zhengneng** [comment]
seems completely fine.

**Comment by sruan2** [comment]
Could you give a screenshot?

**Comment by Zhengneng** [comment]
![image](https://user-images.githubusercontent.com/3099927/36233112-4835372a-1199-11e8-8b81-146f9e68ed83.png)

**Comment by Zhengneng** [comment]
![image](https://user-images.githubusercontent.com/3099927/36233146-613d8a38-1199-11e8-8bef-294653e1abb9.png)

**Comment by Zhengneng** [comment]
![image](https://user-images.githubusercontent.com/3099927/36233165-7902b79c-1199-11e8-9244-ea064682d1e1.png)

**Comment by Zhengneng** [comment]
![image](https://user-images.githubusercontent.com/3099927/36233175-87d0d02e-1199-11e8-9dd7-3aaee77c5c23.png)

**Comment by Zhengneng** [comment]
These screenshots are from the same device like I tested last week.

**Comment by Zhengneng** [comment]
![image](https://user-images.githubusercontent.com/3099927/36515621-25d610aa-172f-11e8-870f-706f6b808a2d.png)

**Comment by Zhengneng** [comment]
is there any update on this ticket?

**Comment by sruan2** [comment]
I will close it for now since the display issue only happens on certain devices and there is not good solution right not.
