### ISSUE TITLE
Fix conversation logic

### ISSUE THREAD

**Issue by sruan2** [sruan2/QuizBot#74]
The logic seems wrong here:

![IMG_5314.PNG](https://images.zenhubusercontent.com/5a3a08148a75884b908bb845/757cf962-9e29-44e2-87bb-2361b3011a67)

**Comment by Zhengneng** [comment]
Confirmed I also saw this issue once this morning when I was testing.
However after that this issue never showed up anymore...

![image](https://user-images.githubusercontent.com/3099927/36077236-e1d5af74-0f1c-11e8-8f78-0194840c8d6f.png)

**Comment by Zhengneng** [comment]
I tested about another 10 times and didn't show up anymore. Pretty weird since Hi is never a keyword here.

**Comment by Zhengneng** [comment]
![image](https://user-images.githubusercontent.com/3099927/36077261-6a005502-0f1d-11e8-93f7-5a40dd2ecce2.png)

also, when input is [thumb up], the program will stop.

**Comment by sruan2** [comment]
What did the error message say?

**Comment by Zhengneng** [comment]
I didn't see anything was captured in the log by entering [thumb up]

**Comment by sruan2** [comment]
We should clean up the code in chatbot.py. There're redundancies and the state machine is not clearly coded, which makes the program easy to enter some state we would not expect.

**Comment by Zhengneng** [comment]
Sure
